RestaurantManagement.UI/Areas/Admin/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RestaurantManagement.Data.Abstract;
using RestaurantManagement.Domain.Enums;
using RestaurantManagement.Service.Abstracts;
using RestaurantManagement.UI.Areas.Admin.Models;

namespace RestaurantManagement.UI.Areas.Admin.Controllers
{

    public class CategoriesController : BaseController
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly ICategoriesService _categoriesService;

        public CategoriesController(IUnitOfWork unitOfWork, ICategoriesService categoriesService)
        {
            _unitOfWork = unitOfWork;
            _categoriesService = categoriesService;
        }
        public IActionResult Index()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GetDataCategory(RequestDatatable requestDatatable)
        {

            var result = await _categoriesService.GetAllCaterories(requestDatatable);

            return Json(result); // = Ok()
        }

        [HttpGet]
        public async Task<IActionResult> InsertUpdate(int id)
        {

            if (id == 0)
            {
                return View(new CategoryModel());
            }

            var category = await _unitOfWork.CategoryRepository.GetById(id);

            var catvm = new CategoryModel
            {
                Id = category.Id,
                Name = category.Name
            };
            return View(catvm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> InsertUpdate(CategoryModel categoryModel)
        {
            if(ModelState.IsValid)
            {
                var result = await _categoriesService.CreateUpdate(categoryModel);
                if (result.Status && result.StatusType == StatusType.Success)
                {
                    return RedirectToAction("Index", "categories");
                }
                else
                {
                    ViewBag.Error = result.Message;
                }
            }
            else
            {
                ViewBag.Error = "Validate mode invalid";
            }

            return View();
        }


        [HttpDelete]
        public async Task<IActionResult> Delete(int key)
        {
            await _categoriesService.DeleteCategory(key);
            return Json(true);
        }
    }
}

RestaurantManagement.UI/Areas/Admin/Controllers/RoleController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RestaurantManagement.Domain.Enums;
using RestaurantManagement.Service.Abstracts;
using RestaurantManagement.UI.Areas.Admin.Models;

namespace RestaurantManagement.UI.Areas.Admin.Controllers
{

    public class RoleController : BaseController
    {
        private readonly IRoleService _roleService;
        private readonly RoleManager<IdentityRole> _roleManager;


        public RoleController(IRoleService roleService, RoleManager<IdentityRole> roleManager) 
        {
            _roleService = roleService;
            _roleManager = roleManager;
 
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GetDataRole(RequestDatatable requestDatatable)
        {

            var result = await _roleService.GetListRole(requestDatatable);

            return Json(result);

        }

        [HttpGet]
        public async Task<IActionResult> CreateUpdate(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                ViewBag.IsEdit = false;
                return View();
            }

            ViewBag.IsEdit = true;

            var role = await _roleManager.FindByIdAsync(id);

            var roleVM = new RoleViewModel
            {
                Id = id,
                Name = role.Name
                
            };
            return View(roleVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateUpdate(RoleViewModel roleViewModel)
        {
            if (ModelState.IsValid)
            {
                //insert
                var result = await _roleService.CreateUpdate(roleViewModel);

                if (result.Status && result.StatusType == StatusType.Success)
                {
                    return RedirectToAction("Index", "role");
                }
                else
                {
                    ViewBag.IsEdit = result.Action == ActionType.Insert ? false : true;
                    ViewBag.Error = result.Message;
                }

            }
            else
            {
                ViewBag.Error = "Validate mode invalid";
            }
            return View();
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(string key)
        {
            await _roleService.DeleteRole(key);

            return Json(true);
        }
    }
}

RestaurantManagement.UI/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using RestaurantManagement.Service.Abstracts;
using RestaurantManagement.Service.DTOs.Cart;
using RestaurantManagement.UI.wwwroot.admin.Utility;

namespace RestaurantManagement.UI.Controllers
{
    public class CartController : BaseController
    {
        const string SessionKeyCart = "_SessionCart";
        private readonly IFoodService _foodService;

        public CartController(IFoodService foodService) 
        {
            _foodService = foodService;
        }


        
        public async Task<IActionResult> Index()
        {
            var carts = HttpContext.Session.Get<List<CartModel>>(SessionKeyCart);

            if(carts is null)
            {
                ViewBag.Food = null;
                return View();

            }

            var result = await _foodService.GetItemFood(carts);

            ViewBag.Food = result;

            return View();
        }

        [HttpPost]
        public IActionResult SaveItem([FromBody] CartModel cartModel)
        {
            try
            {
                var ls = new List<CartModel>();

                var carts = HttpContext.Session.Get<List<CartModel>>(SessionKeyCart); //A-2, B-4

                if (carts is null)
                {
                    ls.Add(cartModel);
                    HttpContext.Session.Set<List<CartModel>>(SessionKeyCart, ls);

                    return Json(true);
                }

                var oldCart = carts.FirstOrDefault(x => x.Code == cartModel.Code); //3

                if (oldCart is null)
                {
                    carts.Add(cartModel);
                }
                else
                {
                    oldCart.Quantity += cartModel.Quantity;
                }

                HttpContext.Session.Set<List<CartModel>>(SessionKeyCart, carts);


                return Json(true);
            }
            catch (Exception)
            {
                return Json(false);
            }
        }

        [HttpPost]
        public IActionResult UpdateCart([FromBody] List<CartModel> cartModel)
        {
            try
            {

                HttpContext.Session.Set(SessionKeyCart, cartModel);


                return Json(true);
            }
            catch (Exception)
            {
                return Json(false);
            }
        }
    }
}

RestaurantManagement.UI/Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;
using RestaurantManagement.Service.Abstracts;

namespace RestaurantManagement.UI.Controllers
{
    public class MenuController : BaseController
    {
        private readonly IMenuService _menuService;
        private readonly IFoodService _foodService;

        public MenuController(IMenuService menuService, IFoodService foodService)
        {
            _menuService = menuService;
            _foodService = foodService;
        }

        public async Task<IActionResult> Index()
        {


            var lsMenu = await _foodService.GetFoodByMenu();

            return View(lsMenu);
        }



    }
}

RestaurantManagement.UI/Areas/Admin/Views/Shared/_Footer.cshtml
<div class="nk-footer">
    <div class="container-fluid">
        <div class="nk-footer-wrap">
            <div class="nk-footer-copyright">
                &copy; 2023 DashLite. Template by <a href="https://softnio.com" target="_blank">Softnio</a>
            </div>
        </div>
    </div>
</div>

RestaurantManagement.UI/Areas/Admin/Views/Shared/_Header.cshtml
@using System.Security.Claims;

<div class="nk-header nk-header-fixed is-light">
    <div class="container-fluid">
        <div class="nk-header-wrap">
            <div class="nk-menu-trigger d-xl-none ms-n1">
                <a href="#" class="nk-nav-toggle nk-quick-nav-icon" data-target="sidebarMenu"><em class="icon ni ni-menu"></em></a>
            </div>
            <div class="nk-header-brand d-xl-none">
                <a href="html/index.html" class="logo-link">
                    <img class="logo-light logo-img" src="~/admin/assets/images/logo.png" srcset="~/admin/assets/images/logo2x.png 2x" alt="logo">
                    <img class="logo-dark logo-img" src="~/admin/assets/images/logo-dark.png" srcset="~/admin/assets/images/logo-dark2x.png 2x" alt="logo-dark">
                </a>
            </div><!-- .nk-header-brand -->
            <div class="nk-header-tools">
                <ul class="nk-quick-nav">
                    <li class="dropdown user-dropdown">
                        <a href="#" class="dropdown-toggle" data-bs-toggle="dropdown">
                            <div class="user-toggle">
                                <div class="user-avatar sm">
                                    <img src="~/images/@(User.FindFirst(ClaimTypes.NameIdentifier)?.Value).png" class="avatar-style-sm" />
                                </div>
                                <div class="user-info d-none d-md-block">
                                    <div class="user-status">@User.Identity.Name</div>
                                    <div class="user-name dropdown-indicator">@User.Identity.Name</div>
                                </div>
                            </div>
                        </a>
                        <div class="dropdown-menu dropdown-menu-md dropdown-menu-end dropdown-menu-s1">
                            <div class="dropdown-inner">
                                <ul class="link-list">
                                    <li>
                                        <a asp-controller="authentication" asp-action="logout"
                                           method="post"><em class="icon ni ni-signout"></em><span>Sign out</span></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </li>
                </ul><!-- .nk-quick-nav -->
            </div><!-- .nk-header-tools -->
        </div><!-- .nk-header-wrap -->
    </div><!-- .container-fliud -->
</div>

RestaurantManagement.UI/Areas/Admin/Views/Shared/_Layout.cshtml
@using System.Security.Claims;
<!DOCTYPE html>
<html lang="zxx" class="js">

<head>
    <base href=".">
    <meta charset="utf-8">
    <meta name="author" content="Softnio">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="A powerful and conceptual apps base dashboard template that especially build for developers and programmers.">
    <!-- Fav Icon  -->
    <link rel="shortcut icon" href="~/admin/assets/images/favicon.png">
    <!-- Page Title  -->
    <title>Blank - Layout | DashLite Admin Template</title>
    <!-- StyleSheets  -->
    <link rel="stylesheet" href="~/admin/assets/css/dashlite.css?ver=3.2.2">
    <link id="skin-default" rel="stylesheet" href="~/admin/assets/css/theme.css?ver=3.2.2">
    <link href="~/admin/assets/css/libs/themify-icons.css" rel="stylesheet" />
    <link href="~/lib/jquery-confirm/jquery-confirm.min.css" rel="stylesheet" />
    <link href="~/lib/toaster/naranja.min.css" rel="stylesheet" />
</head>

<body class="nk-body bg-lighter npc-general has-sidebar ">
    <div class="nk-app-root">
        <!-- main   -->
        <div class="nk-main ">
            <!-- sidebar   -->
            <partial name="_SideBar.cshtml" />
            <!-- sidebar    -->
            <!-- wrap   -->
            <div class="nk-wrap ">
                <!-- main header   -->
                <partial name="_Header.cshtml" />
                <!-- main header    -->
                <!-- content   -->
                <div class="nk-content ">
                    <div class="container-fluid">
                        <div class="nk-content-inner">
                            <div class="nk-content-body">
                                @RenderBody()
                            </div>
                        </div>
                    </div>
                </div>
                <!-- footer    -->
                <partial name="_Footer.cshtml" />
            </div>
        </div>
    </div>

    <!-- JavaScript -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-confirm/jquery-confirm.min.js"></script>
    <script src="~/lib/toaster/naranja.min.js"></script>
    <script src="~/admin/assets/js/nioapp.min.js"></script>
    <script src="~/admin/assets/js/scripts.js"></script>

    @RenderSection("Scripts", required: false)
</body>

</html>

RestaurantManagement.UI/Areas/Admin/Views/Shared/_SideBar.cshtml
<div class="nk-sidebar nk-sidebar-fixed is-dark " data-content="sidebarMenu">
    <div class="nk-sidebar-element nk-sidebar-head">
        <div class="nk-menu-trigger">
            <a href="#" class="nk-nav-toggle nk-quick-nav-icon d-xl-none" data-target="sidebarMenu"><em class="icon ni ni-arrow-left"></em></a>
            <a href="#" class="nk-nav-compact nk-quick-nav-icon d-none d-xl-inline-flex" data-target="sidebarMenu"><em class="icon ni ni-menu"></em></a>
        </div>
        <div class="nk-sidebar-brand">
            <a href="@Url.Action("Index", "home")" class="logo-link nk-sidebar-logo">
                <img class="logo-light logo-img" src="~/admin/assets/images/logo.png" srcset="~/admin/assets/images/logo2x.png 2x" alt="logo">
                <img class="logo-dark logo-img" src="~/admin/assets/images/logo-dark.png" srcset="~/admin/assets/images/logo-dark2x.png 2x" alt="logo-dark">
            </a>
        </div>
    </div><!-- .nk-sidebar-element -->
    <div class="nk-sidebar-element nk-sidebar-body">
        <div class="nk-sidebar-content">
            <div class="nk-sidebar-menu" data-simplebar>
                <ul class="nk-menu">
                    <li class="nk-menu-item has-sub">
                        <a href="#" class="nk-menu-link nk-menu-toggle">
                            <span class="nk-menu-icon"><em class="icon ni ni-dot-box"></em></span>
                            <span class="nk-menu-text">System</span>
                        </a>
                        <ul class="nk-menu-sub">
                            <li class="nk-menu-item">
                                <a href="@Url.Action("Index", "Account")" class="nk-menu-link">
                                    <span class="nk-menu-text">Account</span>
                                </a>
                            </li>
                            <li class="nk-menu-item">
                                <a href="@Url.Action("Index", "Role")" class="nk-menu-link">
                                    <span class="nk-menu-text">Role</span>
                                </a>
                            </li>
                        </ul><!-- .nk-menu-sub -->
                    </li><!-- .nk-menu-item -->
                    <li class="nk-menu-item has-sub">
                        <a href="#" class="nk-menu-link nk-menu-toggle">
                            <span class="nk-menu-icon"><em class="icon ni ni-dot-box"></em></span>
                            <span class="nk-menu-text">Management</span>
                        </a>
                        <ul class="nk-menu-sub">
                            <li class="nk-menu-item">
                                <a href="@Url.Action("Index", "Categories")" class="nk-menu-link">
                                    <span class="nk-menu-text">Category</span>
                                </a>
                            </li>
                            <li class="nk-menu-item">
                                <a asp-controller="food" asp-action="index" asp-area="admin" class="nk-menu-link">
                                    <span class="nk-menu-text">Food</span>
                                </a>
                            </li>
                            <li class="nk-menu-item">
                                <a href="@Url.Action("Index", "Menu")" class="nk-menu-link">
                                    <span class="nk-menu-text">Menu</span>
                                </a>
                            </li>
                            <li class="nk-menu-item">
                                <a href="@Url.Action("Index", "Cart")" class="nk-menu-link">
                                    <span class="nk-menu-text">Cart</span>
                                </a>
                            </li>
                            <li class="nk-menu-item">
                                <a href="@Url.Action("Index", "UserAddress")" class="nk-menu-link">
                                    <span class="nk-menu-text">User Address</span>
                                </a>
                            </li>
                        </ul><!-- .nk-menu-sub -->
                    </li><!-- .nk-menu-item -->
                </ul><!-- .nk-menu -->
            </div><!-- .nk-sidebar-menu -->
        </div><!-- .nk-sidebar-content -->
    </div><!-- .nk-sidebar-element -->
</div>